<?php
//$Id$


/**
 * @file
 *
 * Add custom fields to site wide contact form
 *
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */



/**
 * Implementation of hook_menu
 * 
 * @return $item
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_menu() {
  $item = array();
  $item['admin/build/contact/manage'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => "Manage fields",
    'title callback' => 't',
    'page callback' => 'contact_field_list_field',
    'access arguments' => array('administer site configuration'),
    'file' => 'contact_field_admin.inc',
    'file path' => drupal_get_path('module', 'contact_field'),
    'weight' => 50,
  );

  $item['admin/build/contact/add/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'contact_field_add_field',
    'page arguments' => array(4),
    'access arguments' => array('administer site configuration'),
    'file' => 'contact_field_admin.inc',
    'file path' => drupal_get_path('module', 'contact_field'),
  );
  
  $item['admin/build/contact/%/edit'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'contact_field_add_field',
    'page arguments' => array(3, TRUE),
    'access arguments' => array('administer site configuration'),
  );
  
  $item['admin/build/contact/%/delete'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'contact_field_delete_field',
    'page arguments' => array(3),
    'access arguments' => array('administer site configuration'),
  );

  return $item;
}



/**
 * Implementation of hook_form_FORM_ID_alter
 * 
 * @param $form
 * @param $form_state
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_form_contact_mail_page_alter(&$form, $form_state) {
  $am__elements = _get_field_details();
  if (!empty($am__elements)) {
	  foreach ($am__elements as $name => $value) {
	    $form[$name] = $value;
	  }
  }
  
  $form['submit']['#weight'] = 10;
}



/**
 * _get_field_details
 * 
 * Return created fields
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function _get_field_details() {
  $r__result = db_query("SELECT * FROM {contact_fields} WHERE enabled = 1");
  while($om__result = db_fetch_object($r__result)) {
    $am__settings = unserialize($om__result->settings);
    $am__field[$om__result->field_name] = array(
      '#type' => $om__result->field_type,
      '#title' => $am__settings['title'],
      '#required' => $om__result->required,
      '#weight' => $om__result->weight,
    );
    foreach ($am__settings as $key => $value) {
    	$am__field[$om__result->field_name]["#". $key] = $value;
    } 
  }
  return $am__field;
}



/**
 * contact_field_delete_field
 * 
 * @param string $ss__field_name
 *  The field name to be deleted
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_delete_field($ss__field_name) {
	if ($ss__field_name) {
		db_query("DELETE FROM {contact_fields} WHERE field_name = '%s'", $ss__field_name);
		drupal_goto("admin/build/contact/manage");
	}
	
}


function contact_field_edit_field($ss__field) {
	if ($ss__field) {
	  module_load_include('inc', 'contact_field', 'contact_field_admin');
		$ss__field_type = db_result(db_query("SELECT field_type FROM {contact_fields} 
	    WHERE field_name = '%s'", $ss__field));
	  switch($ss__field_type) {
	    case 'textfield':
	      return drupal_get_form('contact_field_add_field_text_form', $form_state, $ss__field, TRUE);
	  }
	}
}


/**
 * _get_field_values
 * 
 * Return all the details related to a field
 * 
 * @param array $ss__field
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function _get_field_values($ss__field) {
	if ($ss__field) {
		$r__result_field = db_query("SELECT * FROM {contact_fields} WHERE 
		  field_name = '%s'", $ss__field);
		while ($om__result_field = db_fetch_object($r__result_field)) {
			$am__field = unserialize($om__result_field->settings);
			$am__field_value['name'] = $om__result_field->field_name;
			$am__field_value['title'] = $am__field['title'];
			$am__field_value['weight'] = $om__result_field->weight;
			$am__field_value['required'] = $om__result_field->required;
			$am__field_value['enabled'] = $om__result_field->enabled;
		}
		
		return $am__field_value;
	}
}



/**
 * contact_field_filter_xss
 * 
 * Filter the provided string for restricted html tags
 * 
 * @param string $ss__string
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_filter_xss($ss__string) {
	return filter_xss($ss__string, _contact_field_allowed_tags());
}


/**
 * _contact_field_allowed_tags
 * 
 * Return tags to be filtered from allowed values
 * 
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function _contact_field_allowed_tags() {
	return array('a', 'b', 'big',  'code', 'del', 'em', 'i', 'ins',  'pre', 'q', 'small', 'span', 'strong', 'sub', 'sup', 'tt', 'ol', 'ul', 'li', 'p', 'br', 'img');
}


/**
 * _get_field_type
 * 
 * Return type of the field
 * 
 * @param string $ss__field_name
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function _get_field_type($ss__field_name) {
	return db_result(db_query("SELECT field_type FROM {contact_fields} 
	 WHERE field_name = '%s'", $ss__field_name));
}


/**
 * Implementation of hook_mail_alter
 * 
 * @param unknown_type $message
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_mail_alter($message) {
	$am__fields = _get_enabled_fields();
	$ss__addtional = t("Addtional information") ."/\n/\r";
	foreach ($am__fields as $field => $lable) {
		if (is_array($message['params'][$field])) {
			$ss__addtional .= $label ."/\n/\r";
			foreach ($message['params'][$field] as $key => $value) {
				$ss__addtional .= $key .": ". $value ."/\n/\r";
			}
		}
		else {
			$ss__addtional .= $lable .":". $message['params'][$field]; 
		}
	}
}


/**
 * _get_enabled_fields
 * 
 *  Return all the enabled fields
 *  
 *  @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function _get_enabled_fields() {
	$r__result = db_query("SELECT field_name, settings FROM {contact_fields} WHERE  enabled = 1");
	while ($om__result = db_fetch_object($r__result)) {
		$am__settings = unserialize($om__result->settings);
		$am__field[$om__result->field_name] = $am__settings['title'];
	}
	return $am__field;
}