<?php
//$Id$


/**
 * @file
 * 
 * Add select box on contact form
 * 
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */


/**
 * 
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_listfield_info() {
	return array(
	  'select' => array(
	    'type' => 'list',
	    'title' => t("List"),
	    'description' => t("Add select box on contact form"),
	  ),
	);
}




/**
 * 
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_add_field_listfield_form() {
	drupal_set_title(t("Configure list field"));
	$am__field_values = _get_field_values($ss__field);
  $form['field_type'] = array(
    '#type' => 'hidden',
    '#default_value' => 'select',
  );
  
  $form['contact_field_name'] = array(
    '#type' => 'textfield',
    '#title' => t("Field name"),
    '#description' => t("Machine readable name of the field. This should only
      contain alphanumaric charachters and underscore."),
    '#required' => TRUE,
    '#weight' => -50,
  );
  
  $form['contact_field_label'] = array(
    '#type' => 'textfield',
    '#title' => t("Field title"),
    '#description' => t("Provide the title of the field"),
    '#default_value' => $am__field_values['title'],
    '#required' => TRUE,
    '#weight' => -49,
  );
  
  $form['contact_field_num_value'] = array(
    '#type' => 'select',
    '#title' => t("Number of value"),
    '#description' => t("Number of values allowed to enter. If 'Single' 
      is selected, only one value can be selected."),
    '#options' => array(
      0 => t("Single"),
      1 => t("Multiple"),
    ),
    '#default_value' => $am__field_values['num_value'],
    '#required' => TRUE,
    '#weight' => -48,
  );
  
  $form['contact_field_prefix'] = array(
    '#type' => 'textfield',
    '#title' => t("Prefix"),
    '#description' => t("Add prefix to add style to the field."),
    '#default_value' => $am__field_values['prefix'],
    '#weight' => -47,
  );
  
  $form['contact_field_suffix'] = array(
    '#type' => 'textfield',
    '#title' => t("Suffix"),
    '#description' => t("Add suffix to add style to the field."),
    '#default_value' => $am__field_values['suffix'],
    '#weight' => -46,
  );
  
  $form['contact_field_require'] = array(
    '#type' => 'radios',
    '#title' => t("Required?"),
    '#description' => t("Whether this field is mandatory."),
    '#default_value' => (!empty($am__field_values['required']) ? $am__field_values['required'] : 1),
    '#options' => array(
      0 => t("No"),
      1 => t("Yes"),
    ),
    '#required' => TRUE,
    '#weight' => -45,
  );

  $form['contact_field_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t("Display this field"),
    '#description' => t("Check this box to make this field available on 
      contact form."),
    '#default_value' => (!empty($am__field_values['enabled']) ? $am__field_values['enabled'] : 1),
    '#weight' => -44,
  );

  $form['contact_field_weight'] = array(
    '#type' => 'textfield',
    '#title' => t("Weight"),
    '#size' => 10,
    '#description' => t("Fields with positive weight will sink. 
      Negative weight will make the field pop up."),
    '#default_value' => (!empty($am__field_values['weight']) ? $am__field_values['weight'] : 0),
    '#weight' => -43,
  );

  $form['contact_field_vlaues'] = array(
    '#type' => 'textarea',
    '#title' => t("Allowed values"),
    '#description' => t("Add key-value pair in key|value format. Add each pair in separate line."),
    '#default_value' => (!empty($am__field_values['values']) ? $am__field_values['values'] : ""),
    '#weight' => -42,
  );

  $form['contact_field_help'] = array(
    '#type' => 'textarea',
    '#title' => t("Help text"),
    '#description' => t("Help text will appear just beneath the field like this, 
      to help user in filling value in the field."),
    '#default_value' => (!empty($am__field_values['help']) ? $am__field_values['help'] : ""),
    '#weight' => -41,
  );
  
  $form['contact_field_submit'] = array(
    '#type' => 'submit',
    '#value' => t("Save configuration"),
  );
  
  $form['#submit'] = array('contact_field_listfield_submit');
  
  return $form;
}



function contact_field_listfield_submit($form, $form_values) {
  $ss__num_values = $form_values['values']['contact_field_num_value'];
  if ($ss__num_values) {
    $ss__field_settings['multiple'] = TRUE;
  }
  else {
    $ss__field_settings['multiple'] = FALSE;
  }
	$ss__field_name = $form_values['values']['contact_field_name'];
  $ss__field_type = $form_values['values']['field_type'];
  $ss__field_required = $form_values['values']['contact_field_require'];
  $ss__field_enabled = $form_values['values']['contact_field_enabled'];
  $ss__field_settings['title'] = $form_values['values']['contact_field_label'];
  $ss__field_settings['prefix'] = $form_values['values']['contact_field_prefix'];
  $ss__field_settings['suffix'] = $form_values['values']['contact_field_suffix'];
  $ss__field_weight = $form_values['values']['contact_field_weight'];
  $ss__field_settings['description'] = $form_values['values']['contact_field_help'];
  $am__options = explode("\n", $form_values['values']['contact_field_vlaues']);
  foreach ($am__options as $option) {
    var_dump($am__options);
    $option = contact_field_filter_xss($option);
    if (strpos($option, '|') !== FALSE) {
      list($key, $value) = explode("|", $option);
      $ss__field_settings['options'][$key] = $value;
    }
  }

  db_query("INSERT INTO {contact_fields} VALUES('%s', '%s', '%s', %d, %d, '%s')",
    $ss__field_name, $ss__field_type, serialize($ss__field_settings),
    $ss__field_required, $ss__field_enabled, $ss__field_weight);
  drupal_set_message($ss__field_settings['title'] ." ". t("created"));
  drupal_goto('admin/build/contact/manage');
}